name: Auto-merge Release PR

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-release:
    name: Auto-merge Release Please PR
    runs-on: ubuntu-latest
    if: |
      (github.event.pull_request.user.login == 'github-actions[bot]' || github.event.pull_request.user.login == 'BlueConfetti') &&
      startsWith(github.event.pull_request.title, 'chore(main): release')
    steps:
      - name: Merge release PR
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
